{% set version = "0.0-54.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gwidgets
  version: {{ version|replace("-", "_") }}

source:
  fn: gWidgets_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gWidgets_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gWidgets/gWidgets_{{ version }}.tar.gz
  sha256: c2b28b146de38c7ecb86046f5876080a439c34632cc9c1dde0ff2d4ae2959cef

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('gWidgets')"  # [not win]
    - "\"%R%\" -e \"library('gWidgets')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/gWidgets/index.html
  license: GPL (>= 2)
  summary: gWidgets provides a toolkit-independent API for building interactive GUIs. At least
    one of the 'gWidgetsXXX packages', such as gWidgetstcltk, needs to be installed.
    Some icons are on loan from the scigraphica project http
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
