# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "yHDHksJo8zv3B1EnAVMvGktIJFujkpb2jQh2+bPHG48s8a5coI3/AzAP60vO+Sw86rZTngopMQLVU7fisoGgfdMq8ZrdTrBe45LbwxpRC9Hpvb0g6YYk/du79Z8SrLVvFVXGY4wWcpb/TdMPr0FPuZoYsbyDpJVZecN6foe+G1wB3/qb1W19/WYzPUYmMKFxpNUxs/tniPxANHKfsmZW9090O9ukVXtTOZ16gkcMHYEVHT+hjITkDqYwcn6dhYDmEmH8pMiR4IupJiIwhpoLJAx/LDrzwRRP7HRb9aaPV4svzk/SgUESWGarXjX21HuuQ+jy1jxGwyNjY1uD5sLx3kOqejj8aZ+UP/xtYIo42no90JgD6giymF0eznuIxSiYQoTLWgjTGDdNhN2hYcpe4a3qhPMWZ5G1UZ4nkonavSccGl8zEXEAvTT+yUmjsG57ASmZ4hAJY2X86JgKClPOHbD25N1eT1DDOEV1gtre0LDM9kl0uX7LferDk3XgT6z5SDHmp6HpYSjUlTSD4ihWiVSlxjjnk9xGeY/uqsQYEFKCqgjz+xm5+IZaKG8+ld0AlaTuzMXZcoAL142gzkMiisAZUAu5q4rFYI6idsJmSGcgHUotYgCKkjmHVND+yZcwuGosAPIh9MNuBUfnDwH/9A+znhhzG17pJXnFbovY0N0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
