travis:
  secure:
    BINSTAR_TOKEN: hS1ORSQ3ooUkrE2Woj/J8SxfsRn8YzuKuPgVKMO/exDnFZ9knjA8ihms05srMgTVV0UVlojJ/R7SFjfWN88F5nvjVhwhMAh4LRs6RtqIwypFCSASO3VYwzVTKL5PrLt/pLo0hoYhUavvf9shrJKBWRlTSoYfv74qmmnV8J0+nHAgljLU3R24YSrx1anRlZgrunMesGmyKJE+1zB9nucv4ktYBXL2jvPQpdIYYhZyQaFMKvH+jeZot+ZVWt/yaEhIroHK4/n+ha2VNCZK6HJ19sCdWQvUxJFAGwbnJOHVfDsLumQtQmFgXca4fVK/PfvsWvIiun8Ec3x4M/jsb1XpRvJA+ru/b1r39kAjTIweUIwRJAydSSFYeSwz+lfA0rZ4paZPAqh5JFzKFHW5fa6ePm6bes412dAdn/JbUzvTfyNgO/3fpAdExnoSOBxUUgUWuQKyMOb047F9w4lCM4UGywVP0iICX0b7eWjMn6aCgEtE/vMHaBS6dcOefrHO5kQSzFzCBVrdxdzWF0mlnNx2crtmOH0eBGzKzcYhkPmY6O+dSfkogavyDEC9gT2eN/Njg1f2LSlLRX43QlvrS3Rfv9v9EUWBo/vGTnthZsknGT0tNxzg+YxpuotD0BAFDrWA7m+QCrwXI7ZaGRjN4ncrMb55Vyg1hHI2esc/UfJhnZI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
