travis:
  secure:
    BINSTAR_TOKEN: LtEZp/RIjKjV3T5UlcKiZBPTRs1/UfsyvsCEElpEe1/X3PnsP+uaY2mMnUkwq8lZxOYO3y19R0t29iDF7FjcJ2dqLs7mwAMayDGus8McO2/Id5VdWs7lLeqVuaQdKhxNVTZURCqsSw2VpyV2R9oC/AwiTYOlw86A1y1hMRyR4zLznMZkYHHAGGi6MEexWy99K/VR+117EXj8SqnmhvOx7kJosdeduyTn9SA6ZkxOVdVKXsGIkW87Q1lUt+KNwNlW6SO53FZGJCwnorOf29InH4EMEvebfl83kSnNQYT+Ugx8WPFRVxPf4DH6DlkzMog+CdyqfZtpbxd8BqGc+tMgv4rvESrxI2HQrzihyx5S3HKgS/qhi+NC3jjgG5Ijo+UXjZL2PHxSoeqDW/0bQeJHJhSTZtl4t720di/si+DB3ULt+Q6z2tMg+VZA/8LgApQwiI0NYXjBBsKiRG6O2V/W9iAo4KtEcQnC3E1qkvgHskW1TIRo2K6dfnNaHrLjdcWcdsp2S1Rf0cGFYfKvEk+Sk16+fwEk+fWpuot84dbrbl2l/FYMLjoRdimiiiUF8sZg5eivIrrHol9W6LhcRpPDpUWo0xXvX6MLTkOH0AibykOojAB0YofXyAqJAQnHct0Nyg+jfwDYh7Ka/CxUDqkg1GCZCjCkek6cR9KTadrB5ZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
