travis:
  secure:
    BINSTAR_TOKEN: yHDHksJo8zv3B1EnAVMvGktIJFujkpb2jQh2+bPHG48s8a5coI3/AzAP60vO+Sw86rZTngopMQLVU7fisoGgfdMq8ZrdTrBe45LbwxpRC9Hpvb0g6YYk/du79Z8SrLVvFVXGY4wWcpb/TdMPr0FPuZoYsbyDpJVZecN6foe+G1wB3/qb1W19/WYzPUYmMKFxpNUxs/tniPxANHKfsmZW9090O9ukVXtTOZ16gkcMHYEVHT+hjITkDqYwcn6dhYDmEmH8pMiR4IupJiIwhpoLJAx/LDrzwRRP7HRb9aaPV4svzk/SgUESWGarXjX21HuuQ+jy1jxGwyNjY1uD5sLx3kOqejj8aZ+UP/xtYIo42no90JgD6giymF0eznuIxSiYQoTLWgjTGDdNhN2hYcpe4a3qhPMWZ5G1UZ4nkonavSccGl8zEXEAvTT+yUmjsG57ASmZ4hAJY2X86JgKClPOHbD25N1eT1DDOEV1gtre0LDM9kl0uX7LferDk3XgT6z5SDHmp6HpYSjUlTSD4ihWiVSlxjjnk9xGeY/uqsQYEFKCqgjz+xm5+IZaKG8+ld0AlaTuzMXZcoAL142gzkMiisAZUAu5q4rFYI6idsJmSGcgHUotYgCKkjmHVND+yZcwuGosAPIh9MNuBUfnDwH/9A+znhhzG17pJXnFbovY0N0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
